name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install libraries and run test
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        sh ./test.sh
