name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install composer
      run: curl -sS https://getcomposer.org/installer | php
    - name: Install php libraries
      run: php composer.phar install --ignore-platform-reqs
    - name: Run test
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        sh ./test.sh
